### ISSUE TITLE
Fungerar den här fortfarande?

### ISSUE THREAD

**Issue by appernetic** [NisseBoman/reco-widget#1]
Har inte id oh nyckel ännu så jag kan inte testa den...

**Comment by NisseBoman** [comment]
Hej, har inte heller ett id att testa med längre men bör fungera. Dock har jag noterat att de bytt ut en del i sin design på slutet. 

Du får gärna ta över projektet om du vill.

**Comment by NisseBoman** [comment]
closing and closing this project for good since the api have changed and reco have been bought by Hitta.se
